name: application_base
description: "Unified base for Flutter applications"
version: 0.0.2
homepage: https://github.com/AlexSeednov/application_base

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  # https://pub.dev/packages/auto_route
  #
  # All platform supported
  auto_route: ^9.3.0+1

  # https://pub.dev/packages/connectivity_plus
  #
  # All platform supported
  connectivity_plus: ^6.1.3

  # Base SDK
  flutter:
    sdk: flutter

  # https://pub.dev/packages/get_it
  #
  # All platform supported
  get_it: ^8.0.3

  # https://pub.dev/packages/http
  #
  # All platform supported
  http: ^1.3.0
  
  # https://pub.dev/packages/logger
  #
  # All platform supported
  logger: ^2.5.0

  # https://pub.dev/packages/meta
  #
  # All platform supported
  #
  # flutter_test depends on meta 1.12.0
  meta: ^1.12.0

  # https://pub.dev/packages/rxdart
  #
  # All platform supported
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
