name: application_base
description: "Unified base for Flutter applications"
version: 0.1.2
homepage: https://github.com/AlexSeednov/application_base

environment:
  # Flutter SDK supported versions
  flutter: '>=3.32.5'  

  # Dart SDK supported versions
  # https://docs.flutter.dev/release/archive
  sdk: '>=3.8.1'

# Last update - 05.07.2025
dependencies:
  # All platform supported
  auto_route: 10.1.0+1

  # All platform supported
  connectivity_plus: ^6.1.4

  # All platform supported
  cross_file: ^0.3.4+2

  # Base SDK
  flutter:
    sdk: flutter

  # All platform supported
  flutter_secure_storage: ^9.2.4

  # All platform supported
  get_it: ^8.0.3

  # All platform supported
  hive_ce: ^2.11.3

  # All platform supported
  hive_ce_flutter: ^2.3.1

  # All platform supported
  http: ^1.4.0
  
  # All platform supported
  logger: ^2.6.0

  # All platform supported
  # New Flutter version required
  # meta: ^1.17.0
  meta: 1.16.0

  # All platform supported
  rxdart: ^0.28.0
  
  # All platform supported
  share_plus: 11.0.0

  # All platform supported
  url_launcher: ^6.3.1

#
dev_dependencies:
  #
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
