name: application_base
description: "Unified base for Flutter applications"
version: 0.0.5
homepage: https://github.com/AlexSeednov/application_base

environment:
  # Flutter SDK supported versions
  flutter: '3.29.2'

  # Dart SDK supported versions
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  # https://pub.dev/packages/auto_route
  #
  # All platform supported
  auto_route: ^10.0.1

  # https://pub.dev/packages/connectivity_plus
  #
  # All platform supported
  connectivity_plus: ^6.1.3

  # https://pub.dev/packages/cross_file
  #
  # All platform supported
  cross_file: 0.3.4+2

  # Base SDK
  flutter:
    sdk: flutter

  # https://pub.dev/packages/get_it
  #
  # All platform supported
  get_it: ^8.0.3

  # https://pub.dev/packages/http
  #
  # All platform supported
  http: ^1.3.0
  
  # https://pub.dev/packages/logger
  #
  # All platform supported
  logger: ^2.5.0

  # https://pub.dev/packages/meta
  #
  # All platform supported
  meta: ^1.16.0

  # https://pub.dev/packages/rxdart
  #
  # All platform supported
  rxdart: ^0.28.0

#
dev_dependencies:
  #
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
