name: application_base
description: "Unified base for Flutter applications"
version: 0.0.3
homepage: https://github.com/AlexSeednov/application_base

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  # https://pub.dev/packages/auto_route
  #
  # All platform supported
  auto_route: ^9.3.0+1

  # https://pub.dev/packages/connectivity_plus
  #
  # All platform supported
  connectivity_plus: ^6.1.3

  # Base SDK
  flutter:
    sdk: flutter

  # https://pub.dev/packages/get_it
  #
  # All platform supported
  get_it: ^8.0.3

  # https://pub.dev/packages/http
  #
  # All platform supported
  http: ^1.3.0
  
  # https://pub.dev/packages/logger
  #
  # All platform supported
  logger: ^2.5.0

  # https://pub.dev/packages/meta
  #
  # All platform supported
  #
  # flutter_test depends on meta 1.12.0
  meta: ^1.12.0

  # https://pub.dev/packages/rxdart
  #
  # All platform supported
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
